### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by TomMettam**
"er" is undefined - my bad!

### CODE REVIEW

**Comment by dblock** [comment]
I've merged some of this via https://github.com/alexa-js/alexa-app-server/commit/25789e16111946bfc8553bdb6c00a1cffba97764. I don't understand the `use` change, can you please explain?

I've also added tests in https://github.com/alexa-js/alexa-app-server/pull/23. Would you be so kind to write tests for all the changes, the error one would be a great start.

**Comment by TomMettam** [comment]
This change:

`-                        var ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
 -                        if (ip=="127.0.0.1" || ip=="::ffff:127.0.0.1" || ip=="::1")
 +                        var ip = req.connection.remoteAddress;
 +                        if (!req.headers['x-forwarded-for'] && (ip=="127.0.0.1" || ip=="::ffff:127.0.0.1" || ip=="::1"))
                          {`

was a security fix.  A browser could provide a header like:

X-Forwarded-For: 127.0.0.1

which would allow it to bypass the alexa verification process. This change ensures that X-Forwarded-For is only observed if it's sent from a local server (such as a proxy). Otherwise, the real IP is used.

**Comment by dblock** [comment]
That's fine, and that whole logic moved to alexa-verifier.

I was asking about this:

screen shot 2017-01-18 at 7 40 35 am

**Comment by TomMettam** [comment]
Ah yes - well, that is because bodyParser.urlencoded doesn't necessary work for all the user server modules.

In my project, for example ( https://gyazo.com/bc5b88a444b8ff334b78a5771b3d80c0 ) there are many express routes added which don't use urlencoded forms, so blanket-applying bodyParser.urlencoded to every request causes problems.

**Comment by dblock** [comment]
Oh I see, that makes a lot of sense! I opened https://github.com/alexa-js/alexa-app-server/issues/35 and will close this.

If you have time, would love some tests and a pull request for that issue.

**Pull request closed without merging**
