### PR TITLE
enabled strictHeaderCheck

### PR DESCRIPTION
**Pull request by mreinstein**
#50

### CODE REVIEW

**Comment by dblock** [comment]
Needs changelog and a test please?

**Comment by dblock** [comment]
Much better. Still needs a CHANGELOG line. 

I also winder whether we should add an UPGRADING document that describes breaking changes. Like [this one](https://github.com/alexa-js/alexa-app/blob/master/UPGRADING.md). Feel free to obviously.

**Comment by mreinstein** [comment]
too much process.

**Comment by dblock** [comment]
LOL @mreinstein just trying to have bewildered users wondering why suddenly something returns 401 instead of 200 when they upgrade!

**Comment by mreinstein** [comment]
> just trying to have bewildered users wondering why suddenly something returns 401 instead of 200 when they upgrade!

Better instead to have a broken `alexa-app-server` package that isn't capable of passing alexa certification? ;) Because that's the current situation.

**Comment by dblock** [comment]
Not trying to be difficult. Are you saying a changelog line is too much process? I can merge this as is, but I will be adding that CHANGELOG line next myself ;(

**Comment by mreinstein** [comment]
I know you're not trying to be difficult. And I'm not saying that a changelog in itself is a bad idea. It just feel like a lot more process is in place now.

**Comment by mreinstein** [comment]
2 issues I have with the current changelog:

a ) creating the changelog first, and then doing the release seems backwards to me. for one thing it's impossible to know what the version number will be, when the changes aren't done piling in. It's also confusing at first glance because when I look at a changelog I expect the top item to be the current release, *not* the upcoming release.

b) this isn't so much with the changelog itself but more with shipping modules. It's better to ship small changes frequently rather than piling up tons of stuff in any given release. There is virtually no costs to having additional module versions being published.

these are both hovering in the realm of opinion but I'd rather see quick agile releases that don't try to package too much at once.

**Comment by tejashah88** [comment]
I guess it's bound to happen at some point. As all these libraries grow and mature, we do eventually need more process in order to avoid development of such libraries to be a nightmare. IMO, I don't like more process but to an extent, it's necessary for the future of this library, and maybe others.

**Comment by mreinstein** [comment]
> in order to avoid development of such libraries to be a nightmare

I guess that's where we differ in opinion. I believe these alexa modules are already quite mature and stable. They are in maintenance mode. They don't have extensive features that need to be added, and in fact I believe we should be resisting the urge to massively overhaul or bloat these with new capabilities.

 Not having extensive process did not prevent these modules from being successful or stable, which is why most people are using them in their projects.

**Comment by dblock** [comment]
I agree with most things that you say @mreinstein. And we should discuss process in a separate issue, feel free to open one and propose something better.

**Comment by dblock** [comment]
Merged, thanks!

**Pull request merged**
