### PR TITLE
Error occurs when 'verify' and 'debug' are both set to true

### PR DESCRIPTION
**Pull request by tejashah88**
This PR addresses issue #19.

### CODE REVIEW

**Comment by dblock** [comment]
Before I merge this - should it throw an error instead of silently disabling the debugger since those two options are simply incompatible?

**Comment by tejashah88** [comment]
That might be a better way to handle it. I'll also organize the tests to verify that the debugger is disabled

**Comment by tejashah88** [comment]
One thing though, should is actually throw an error or use `self.error`?

**Comment by dblock** [comment]
This looks good, merging.

**Pull request merged**
