### PR TITLE
Refactored app-server internals.

### PR DESCRIPTION
**Pull request by dblock**
Replaces #54.

### CODE REVIEW

**Comment by dblock** [comment]
I could use some help from @tejashah88 @mreinstein here with these tests and the demo app. With the latest alexa-app I cannot run the debugger in the demo app anymore, things like `app.id` are no longer defined. I am not sure how that worked before - it seems like alexa-app is rendering the test template with `json: self`, so I can definitely do `json.intents` and what not, but I must be missing something bigger.

**Comment by rickwargo** [comment]
Just starting to look at this now. First question - why remove support for having a separate https port? During testing I would like to test http and https, and in production, https. There are multiple reasons to run on a non-standard port - I would like to maintain both ports separately.

**Comment by dblock** [comment]
@rickwargo That was https://github.com/alexa-js/alexa-app-server/issues/46, because no web server AFAIK behaves this way. Binding to HTTP always and HTTPs sometimes as an addon behavior is most problematic, you'd never want this in production - you either run under SSL or you don't (if you do, you can redirect from non-SSL to SSL, but that should be outside the scope of this library). And you can accomplish everything you say with a single `port` option and do any custom logic outside of the library.

**Comment by mreinstein** [comment]
> That was #46, because no web server AFAIK behaves this way. 

no, that's wrong

http://nginx.org/en/docs/http/server_names.html#miscellaneous_names

https://httpd.apache.org/docs/2.4/bind.html

https://kevinworthington.com/lighttpd-mini-howto-using-different-ports-with-same-urlip-address/

The idea that a programs and ports must have a 1:1 relationship is just flat out misinformed. Many programs bind to more than one port.


> binding to HTTP always and HTTPs sometimes as an addon behavior is 
> most problematic, you'd never want this in production

These are assumptions, based on a very rigid idea of "production".

**Comment by rickwargo** [comment]
@dblock I'm not sure I understand your response. I believe the alexa-app-server should be able to listen to different ports using different protocols simultaneously. apache exhibits this behavior. sshd exhibits this behavior. I want to be able to run http and https during development and https in production. I disagree- you need to allow the server to listen to different ports with different protocols simultaneously.

**Comment by mreinstein** [comment]
The number 1 rule of maintaining software: keep the lights on! 

If the software is broken, the maintainers are flat-out failing. I'm not saying this to be mean, I'm just really frustrated that I'm getting emails from users like @cpup22 whom are trying to simply use these modules which used to work, and now don't. It looks like they've been broken for at least a month or more.

I think changelog, code coverage reports, automated test suites are great. But I feel like we're not "seeing the forest for the trees" here. We now have gleaming shiny modules that pass impressive test suites but simply don't work.

Please stop removing features from these modules. Please focus on getting working versions of these modules published to npm. Please test these modules against actual alexa instances so we know when things break.

If you're not willing to do this, assign these alexa modules *back* to me and I'll maintain them myself.

**Comment by rickwargo** [comment]
FYI: My UI that was working prior to #54 no longer works with this (specifically wrt POSTing) - need to take a closer look. Due to limited time, it may take a few days.

**Comment by tejashah88** [comment]
I think one of the bigger problems is the test organization. I do agree with @mreinstein that we just have a bunch of modules that pass test suites but don't work at all. The issue here is that these tests that we've written are almost only to add code coverage or make a module shown as "fully tested", which is not a good mindset to employ when writing tests for **any** library. I do admit that I did this myself but at the time, there was only 65% coverage, which is obviously not great either.

What is really needed is a feature-based testing system, that focuses more on what features are being tested and how well will they work against various scenarios. For example, if I have two `alexa-app-servers`, one on an AWS Lambda instance and one on an express instance, I should have some reassurance that both instances will work identically feature-wise. This would also ideally help us isolate any bugs so that if a certain group of tests of one feature fail, the feature itself would be deemed buggy.

Now how we implement feature-wise testing into this library may take much more planning since there are multiple ways to test xyz feature, although a general format could consist of 2 parts: testing individual features separately and testing against actual apps. The second part shows that we aren't just writing tests for the sake of showcasing a "tried and tested" module.

Note that while I'm not saying that code coverage should be ignored, it isn't a huge priority. IMO, if we implement the feature-wise testing correctly, the code coverage should come automatically.

**Comment by mreinstein** [comment]
@rickwargo 

> specifically wrt POSTing

are you setting `verify: false` when you set up the `alexa-app-server` instance?
I suspect what's happening is alexa-app-server` is using "sane" production defaults. If you don't set  the `verify` field to false it will by default check your POST (and other) requests to make sure they're coming from Amazon.

**Comment by mreinstein** [comment]
@rickwargo feel free to ping me directly on gchat if you want to work through this in real time. Happy to help with debugging, etc. Sorry for any disruptions.

reinstein.mike@gmail.com

**Comment by rickwargo** [comment]
@tejashah88 Good news is I have a feature-based testing approach that I use to test my skills both locally and against lambda. I was reworking the UI to make it easier to use (a replacement of test.ejs) so there are multiple testing (development) paths. I'm working on integrating it with the latest version of alexa-app-server/alexa-app. Hopefully in another week or so I should have something.

**Comment by rickwargo** [comment]
> are you setting verify: false when you set up the alexa-app-server instance?
> I suspect what's happening is alexa-app-serveris using "sane" production defaults. If you don't set theverify` field to false it will by default check your POST (and other) requests to make sure they're coming from Amazon.

I was so excited to try and saw that I have it set to false explicitly :(. I may take you up on your offer, @mreinstein - I'll email to arrange.

**Comment by tejashah88** [comment]
@rickwargo Awesome, I'm looking forward to that. In the meantime, I've opened issue  so that we can discuss about this more in detail. I'm hoping that with this new system, we can squash any remaining bugs we currently have and prevent a number of future bugs from occurring in the first place.

**Comment by dblock** [comment]
I don't feel personal about any of these features, if everyone believes that two options for `port` is what we should have I'm happy to put it back. I was trying to simplify things. It's really not a big deal.

I'd like this code to move forward. The way we do this is by volunteering time. We keep things reliable by writing tests. So... any help with fixing the tests here?

**Comment by dblock** [comment]
I opened https://github.com/alexa-js/alexa-app-server/issues/58 for myself to undo #46.

**Comment by dblock** [comment]
> I'm just really frustrated that I'm getting emails from users like @cpup22 whom are trying to simply use these modules which used to work, and now don't. It looks like they've been broken for at least a month or more

@mreinstein, I am sorry you feel this way, but I cannot agree that these just "used to work", if you look at PRs in alexa-app-server, find a breaking change that worked a month ago - all we've been doing is fixing bugs, writing tests for those bugs, doing a bit of existing functionality tests, and only more recently doing some refactoring

**Comment by dblock** [comment]
> If you're not willing to do this, assign these alexa modules back to me and I'll maintain them myself.

This isn't productive. You have at least @tejashah88 and myself willing to spend real time making things reliable and moving things forward. I have a skill in production using alexa-app, I care about this code being clean, well documented, better tested, and reliable _moving forward_. Here to help.

**Comment by dblock** [comment]
I believe the failures here are legit, the debugger is broken by this change.

**Comment by dblock** [comment]
@rickwargo https://github.com/alexa-js/alexa-app-server/pull/60 reverts the single port change and fixes a number of bugs, would appreciate if you could take a look, too

**Comment by dblock** [comment]
And one more round, closing this in favor of https://github.com/alexa-js/alexa-app-server/pull/64.

**Pull request closed without merging**
